### ISSUE TITLE
弹幕过滤的建议

### ISSUE THREAD

**Issue by isrecalpear** [Dark-Sword-22/danmuG#5]
上传了许多弹幕，里面好多指指点点，看着属实有些不大舒服
希望，啊，抓一些人工审核的ass，不求干活多少，只求踢掉坏哥哥
wo22ne

**Comment by GoodManWEN** [comment]
我觉得再增加一些严格的敏感词过滤是可行的，毕竟弹幕已经多到不嫌少。。

人工审核，啊，那只能留待有缘人了
