### ISSUE TITLE
或许可以尝试逆向投递弹幕？

### ISSUE THREAD

**Issue by sirsereno** [Dark-Sword-22/danmuG#6]
前几天在评论区看到的建议。相比被搬运好哥哥和驻阿B猛男们狠狠塞满的前几P，大部分投稿的后几P往往显得较为冷清。那么或许在搬运暂时无法对大部分投稿实现弹幕全覆盖的情况下，可以将前几P的弹幕完全交给录播观众们手动施工，这边则更改一下弹幕投递逻辑，按时间轴从最后往前逆向投递，完成与手动施工队的大会师。这样一来整体观感可能会更好一些。

**Comment by GoodManWEN** [comment]
是很有道理的建议，但是有一些实际操作层面的问题。

一个问题是，录播自然弹幕其实不是很稳定。直播弹幕经过几个月的观察可以看到一般1P视频内可以覆盖2500-5000条，但录播的话比如[BV1f44y1e7XG](https://www.bilibili.com/video/BV1f44y1e7XG)这种1P有8000条的还好，平时随便玩各种游戏的话，[BV17v411n7tC](https://www.bilibili.com/video/BV17v411n7tC)这种只有两三百条也是很正常的，还有类似近期的卡比等等也是类似情况，对于这些视频如果不投P1的话那么从观看体验的角度讲比较怪，根据UP统计一般来说视频的观看人数从头到尾是持续递减的。以上这些情况导致针对不同情况设定一个统一逻辑做规范看起来比较困难，而如果每一期视频都要手动调整忽略开头弹幕的数量的话维护成本方面有些高，目前server数据也只有两个人在维护。

另一个问题是代码实现方面的问题，设计一个投递概率分布，让后面分P的概率比前面低，但绝对值不低，的这样一种算法其实是很简单的，包括另外一种全随机的思路也可行，但是考虑到目前业务的服务器性能，让服务端“感知“所有待投数据状态，或者全随机，类似的操作，相对于目前的实现方式来说对数据库的压力会大一些。虽然目前这个业务并不占用多少资源，每天收到总请求量可能也就两三万次，因为完全是公益目的的，就我个人而言还是希望服务尽可能轻量。
